// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_debiased_scores_dense
Rcpp::List cpp_debiased_scores_dense(const arma::mat& X, const arma::vec& y, const arma::vec& beta_full, const arma::vec& target_point, const arma::mat& directions);
RcppExport SEXP _HDMaxShrink_cpp_debiased_scores_dense(SEXP XSEXP, SEXP ySEXP, SEXP beta_fullSEXP, SEXP target_pointSEXP, SEXP directionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_full(beta_fullSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type target_point(target_pointSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type directions(directionsSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_debiased_scores_dense(X, y, beta_full, target_point, directions));
    return rcpp_result_gen;
END_RCPP
}
// cpp_debiased_scores_diagonal
Rcpp::List cpp_debiased_scores_diagonal(const arma::mat& X, const arma::vec& y, const arma::vec& beta_full, const Rcpp::IntegerVector& targets, const arma::vec& direction_scale, const arma::vec& target_point);
RcppExport SEXP _HDMaxShrink_cpp_debiased_scores_diagonal(SEXP XSEXP, SEXP ySEXP, SEXP beta_fullSEXP, SEXP targetsSEXP, SEXP direction_scaleSEXP, SEXP target_pointSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_full(beta_fullSEXP);
    Rcpp::traits::input_parameter< const Rcpp::IntegerVector& >::type targets(targetsSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type direction_scale(direction_scaleSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type target_point(target_pointSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_debiased_scores_diagonal(X, y, beta_full, targets, direction_scale, target_point));
    return rcpp_result_gen;
END_RCPP
}
// cpp_multiplier_max
arma::vec cpp_multiplier_max(const arma::mat& psi_centered, const arma::vec& standard_error, const arma::mat& multipliers, const int block_size);
RcppExport SEXP _HDMaxShrink_cpp_multiplier_max(SEXP psi_centeredSEXP, SEXP standard_errorSEXP, SEXP multipliersSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type psi_centered(psi_centeredSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type standard_error(standard_errorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type multipliers(multipliersSEXP);
    Rcpp::traits::input_parameter< const int >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_multiplier_max(psi_centered, standard_error, multipliers, block_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_gaussian_score_max
Rcpp::List cpp_gaussian_score_max(const arma::vec& null_residual, const arma::mat& residualized_tested, const arma::mat& core_basis, const arma::mat& gaussian_draws, const int block_size);
RcppExport SEXP _HDMaxShrink_cpp_gaussian_score_max(SEXP null_residualSEXP, SEXP residualized_testedSEXP, SEXP core_basisSEXP, SEXP gaussian_drawsSEXP, SEXP block_sizeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type null_residual(null_residualSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type residualized_tested(residualized_testedSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type core_basis(core_basisSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type gaussian_draws(gaussian_drawsSEXP);
    Rcpp::traits::input_parameter< const int >::type block_size(block_sizeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_gaussian_score_max(null_residual, residualized_tested, core_basis, gaussian_draws, block_size));
    return rcpp_result_gen;
END_RCPP
}
// cpp_partial_null_geometry
Rcpp::List cpp_partial_null_geometry(const arma::mat& X_core, const arma::mat& X_tested, const double rank_tolerance);
RcppExport SEXP _HDMaxShrink_cpp_partial_null_geometry(SEXP X_coreSEXP, SEXP X_testedSEXP, SEXP rank_toleranceSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X_core(X_coreSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type X_tested(X_testedSEXP);
    Rcpp::traits::input_parameter< const double >::type rank_tolerance(rank_toleranceSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_partial_null_geometry(X_core, X_tested, rank_tolerance));
    return rcpp_result_gen;
END_RCPP
}
// cpp_partial_debiased_scores
Rcpp::List cpp_partial_debiased_scores(const arma::vec& y_residualized, const arma::mat& residualized_tested, const arma::vec& beta_tested);
RcppExport SEXP _HDMaxShrink_cpp_partial_debiased_scores(SEXP y_residualizedSEXP, SEXP residualized_testedSEXP, SEXP beta_testedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y_residualized(y_residualizedSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type residualized_tested(residualized_testedSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_tested(beta_testedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_partial_debiased_scores(y_residualized, residualized_tested, beta_tested));
    return rcpp_result_gen;
END_RCPP
}
// cpp_partial_null_apply
Rcpp::List cpp_partial_null_apply(const arma::vec& y, const arma::mat& coefficient_operator, const arma::mat& orthonormal_basis, const arma::mat& residualized_tested);
RcppExport SEXP _HDMaxShrink_cpp_partial_null_apply(SEXP ySEXP, SEXP coefficient_operatorSEXP, SEXP orthonormal_basisSEXP, SEXP residualized_testedSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type coefficient_operator(coefficient_operatorSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type orthonormal_basis(orthonormal_basisSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type residualized_tested(residualized_testedSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_partial_null_apply(y, coefficient_operator, orthonormal_basis, residualized_tested));
    return rcpp_result_gen;
END_RCPP
}
// cpp_ridge_dual_path
Rcpp::List cpp_ridge_dual_path(const arma::mat& X, const arma::vec& y, const arma::vec& lambda);
RcppExport SEXP _HDMaxShrink_cpp_ridge_dual_path(SEXP XSEXP, SEXP ySEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_ridge_dual_path(X, y, lambda));
    return rcpp_result_gen;
END_RCPP
}
// cpp_mcp_path
Rcpp::List cpp_mcp_path(const arma::mat& X, const arma::vec& y, const arma::vec& lambda, const arma::vec& beta_init, const double gamma, const int max_iter, const double tol, const double zero_tol);
RcppExport SEXP _HDMaxShrink_cpp_mcp_path(SEXP XSEXP, SEXP ySEXP, SEXP lambdaSEXP, SEXP beta_initSEXP, SEXP gammaSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP zero_tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_init(beta_initSEXP);
    Rcpp::traits::input_parameter< const double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const double >::type zero_tol(zero_tolSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_mcp_path(X, y, lambda, beta_init, gamma, max_iter, tol, zero_tol));
    return rcpp_result_gen;
END_RCPP
}
// cpp_operator_norm
double cpp_operator_norm(const arma::mat& X, const arma::mat& A, const int max_iter, const double tol);
RcppExport SEXP _HDMaxShrink_cpp_operator_norm(SEXP XSEXP, SEXP ASEXP, SEXP max_iterSEXP, SEXP tolSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_operator_norm(X, A, max_iter, tol));
    return rcpp_result_gen;
END_RCPP
}
// cpp_sqrt_lasso_pd
Rcpp::List cpp_sqrt_lasso_pd(const arma::mat& X, const arma::vec& y, const double lambda, const arma::mat& A, const arma::vec& target, const arma::vec& penalty_factor, const arma::vec& beta_init, const int max_iter, const double tol, const int check_every, const bool verbose, const double operator_norm_value);
RcppExport SEXP _HDMaxShrink_cpp_sqrt_lasso_pd(SEXP XSEXP, SEXP ySEXP, SEXP lambdaSEXP, SEXP ASEXP, SEXP targetSEXP, SEXP penalty_factorSEXP, SEXP beta_initSEXP, SEXP max_iterSEXP, SEXP tolSEXP, SEXP check_everySEXP, SEXP verboseSEXP, SEXP operator_norm_valueSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A(ASEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type target(targetSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type penalty_factor(penalty_factorSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type beta_init(beta_initSEXP);
    Rcpp::traits::input_parameter< const int >::type max_iter(max_iterSEXP);
    Rcpp::traits::input_parameter< const double >::type tol(tolSEXP);
    Rcpp::traits::input_parameter< const int >::type check_every(check_everySEXP);
    Rcpp::traits::input_parameter< const bool >::type verbose(verboseSEXP);
    Rcpp::traits::input_parameter< const double >::type operator_norm_value(operator_norm_valueSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_sqrt_lasso_pd(X, y, lambda, A, target, penalty_factor, beta_init, max_iter, tol, check_every, verbose, operator_norm_value));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_HDMaxShrink_cpp_debiased_scores_dense", (DL_FUNC) &_HDMaxShrink_cpp_debiased_scores_dense, 5},
    {"_HDMaxShrink_cpp_debiased_scores_diagonal", (DL_FUNC) &_HDMaxShrink_cpp_debiased_scores_diagonal, 6},
    {"_HDMaxShrink_cpp_multiplier_max", (DL_FUNC) &_HDMaxShrink_cpp_multiplier_max, 4},
    {"_HDMaxShrink_cpp_gaussian_score_max", (DL_FUNC) &_HDMaxShrink_cpp_gaussian_score_max, 5},
    {"_HDMaxShrink_cpp_partial_null_geometry", (DL_FUNC) &_HDMaxShrink_cpp_partial_null_geometry, 3},
    {"_HDMaxShrink_cpp_partial_debiased_scores", (DL_FUNC) &_HDMaxShrink_cpp_partial_debiased_scores, 3},
    {"_HDMaxShrink_cpp_partial_null_apply", (DL_FUNC) &_HDMaxShrink_cpp_partial_null_apply, 4},
    {"_HDMaxShrink_cpp_ridge_dual_path", (DL_FUNC) &_HDMaxShrink_cpp_ridge_dual_path, 3},
    {"_HDMaxShrink_cpp_mcp_path", (DL_FUNC) &_HDMaxShrink_cpp_mcp_path, 8},
    {"_HDMaxShrink_cpp_operator_norm", (DL_FUNC) &_HDMaxShrink_cpp_operator_norm, 4},
    {"_HDMaxShrink_cpp_sqrt_lasso_pd", (DL_FUNC) &_HDMaxShrink_cpp_sqrt_lasso_pd, 12},
    {NULL, NULL, 0}
};

RcppExport void R_init_HDMaxShrink(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
