# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Debiased target scores for general precision directions
#'
#' @keywords internal
cpp_debiased_scores_dense <- function(X, y, beta_full, target_point, directions) {
    .Call(`_HDMaxShrink_cpp_debiased_scores_dense`, X, y, beta_full, target_point, directions)
}

#' Debiased coordinate scores for a diagonal precision model
#'
#' @keywords internal
cpp_debiased_scores_diagonal <- function(X, y, beta_full, targets, direction_scale, target_point) {
    .Call(`_HDMaxShrink_cpp_debiased_scores_diagonal`, X, y, beta_full, targets, direction_scale, target_point)
}

#' Multiplier-bootstrap maxima from centered influence scores
#'
#' @keywords internal
cpp_multiplier_max <- function(psi_centered, standard_error, multipliers, block_size = 256L) {
    .Call(`_HDMaxShrink_cpp_multiplier_max`, psi_centered, standard_error, multipliers, block_size)
}

#' Conditional Gaussian score maxima for an exact coordinate null
#'
#' The input residual must be the centered exact-null residual, the tested
#' design must already be residualized off the centered core, and the columns
#' of `core_basis` must be an orthonormal basis for that core. Each Gaussian
#' draw is centered and projected off the core before applying the same
#' residual-scale studentization as the observed statistic.
#'
#' @keywords internal
cpp_gaussian_score_max <- function(null_residual, residualized_tested, core_basis, gaussian_draws, block_size = 256L) {
    .Call(`_HDMaxShrink_cpp_gaussian_score_max`, null_residual, residualized_tested, core_basis, gaussian_draws, block_size)
}

#' SVD geometry for a prespecified low-dimensional core model
#'
#' The routine never forms `(X_core' X_core)^{-1}`.  It returns the
#' Moore--Penrose coefficient operator (after verifying full column rank), an
#' orthonormal basis for the core column space, and every tested column
#' residualized against that space.
#'
#' @keywords internal
cpp_partial_null_geometry <- function(X_core, X_tested, rank_tolerance = 1e-10) {
    .Call(`_HDMaxShrink_cpp_partial_null_geometry`, X_core, X_tested, rank_tolerance)
}

#' One-step scores for the profiled partial square-root LASSO
#'
#' The tested design has already been residualized against the prespecified
#' core.  A diagonal population precision is used, which is appropriate for
#' the Gaussian-iid design studied in the accompanying simulations.  No
#' tested-block covariance matrix is formed or inverted.
#'
#' @keywords internal
cpp_partial_debiased_scores <- function(y_residualized, residualized_tested, beta_tested) {
    .Call(`_HDMaxShrink_cpp_partial_debiased_scores`, y_residualized, residualized_tested, beta_tested)
}

#' Apply cached core-model geometry to a centered response
#'
#' The returned influence scores are the heteroskedasticity-robust,
#' residualized score contributions used by the multiplier-bootstrap maximum
#' test of the coordinate null.
#'
#' @keywords internal
cpp_partial_null_apply <- function(y, coefficient_operator, orthonormal_basis, residualized_tested) {
    .Call(`_HDMaxShrink_cpp_partial_null_apply`, y, coefficient_operator, orthonormal_basis, residualized_tested)
}

#' Dual high-dimensional ridge path
#'
#' Computes ridge estimates from an `n` by `n` eigendecomposition rather than
#' a `p` by `p` inverse. The objective is
#' `||y-X beta||^2/(2n) + lambda ||beta||^2/2`.
#'
#' @keywords internal
cpp_ridge_dual_path <- function(X, y, lambda) {
    .Call(`_HDMaxShrink_cpp_ridge_dual_path`, X, y, lambda)
}

#' MCP coordinate-descent path on all design columns
#'
#' The objective is `||y-X beta||^2/(2n)` plus the coordinatewise MCP
#' penalty. Successive decreasing penalties use warm starts.
#'
#' @keywords internal
cpp_mcp_path <- function(X, y, lambda, beta_init, gamma = 3.0, max_iter = 5000L, tol = 1e-7, zero_tol = 1e-8) {
    .Call(`_HDMaxShrink_cpp_mcp_path`, X, y, lambda, beta_init, gamma, max_iter, tol, zero_tol)
}

#' RcppArmadillo operator norm for the stacked data/restriction operator
#'
#' @keywords internal
cpp_operator_norm <- function(X, A, max_iter = 200L, tol = 1e-9) {
    .Call(`_HDMaxShrink_cpp_operator_norm`, X, A, max_iter, tol)
}

#' RcppArmadillo primal-dual square-root lasso solver
#'
#' @keywords internal
cpp_sqrt_lasso_pd <- function(X, y, lambda, A, target, penalty_factor, beta_init, max_iter = 30000L, tol = 5e-6, check_every = 50L, verbose = FALSE, operator_norm_value = NA_real_) {
    .Call(`_HDMaxShrink_cpp_sqrt_lasso_pd`, X, y, lambda, A, target, penalty_factor, beta_init, max_iter, tol, check_every, verbose, operator_norm_value)
}

